"""reports.py — PDF generation for confirmed violations (hybrid_mvp / Judge Feed).

Two report types:
  - violation_pdf(record, image_path)  -> one-page evidence report
  - summary_pdf(rows, start, end)      -> counts-by-type report for a date range
"""
from __future__ import annotations
from io import BytesIO
from typing import Optional

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.pdfgen import canvas


def violation_pdf(record: dict, image_path: Optional[str]) -> bytes:
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    w, h = A4

    c.setFillColor(colors.HexColor("#ff4757"))
    c.rect(0, h - 25 * mm, w, 25 * mm, fill=True, stroke=False)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 18)
    c.drawString(15 * mm, h - 16 * mm, "TRAFFIC VIOLATION REPORT")

    y = h - 35 * mm
    c.setFillColor(colors.black)
    c.setFont("Helvetica-Bold", 12)
    fields = [
        ("Violation ID", str(record.get("id", "-"))),
        ("Violation Type", str(record.get("violation_type", "-"))),
        ("Vehicle Track ID", str(record.get("vehicle_id", "-"))),
        ("Number Plate", str(record.get("plate_text", "UNKNOWN"))),
        ("Plate Verified", "Yes" if record.get("plate_valid") else "No"),
        ("Frame #", str(record.get("frame_id", "-"))),
        ("Timestamp (UTC)", str(record.get("timestamp", "-"))),
    ]
    for label, value in fields:
        c.setFont("Helvetica-Bold", 11)
        c.drawString(15 * mm, y, f"{label}:")
        c.setFont("Helvetica", 11)
        c.drawString(65 * mm, y, value)
        y -= 8 * mm

    if image_path:
        try:
            y -= 5 * mm
            c.drawImage(image_path, 15 * mm, y - 80 * mm, width=90 * mm, height=80 * mm,
                        preserveAspectRatio=True, anchor="nw")
            y -= 85 * mm
        except Exception:
            pass

    c.setFont("Helvetica-Oblique", 8)
    c.setFillColor(colors.grey)
    c.drawString(15 * mm, 10 * mm, "Generated by HawkEye Traffic Vision — automated detection, human review required.")
    c.showPage()
    c.save()
    return buf.getvalue()


def summary_pdf(rows: list[dict], start: str, end: str) -> bytes:
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    w, h = A4

    c.setFillColor(colors.HexColor("#1a0a0f"))
    c.rect(0, h - 25 * mm, w, 25 * mm, fill=True, stroke=False)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 18)
    c.drawString(15 * mm, h - 16 * mm, "VIOLATION SUMMARY REPORT")

    c.setFillColor(colors.black)
    c.setFont("Helvetica", 11)
    c.drawString(15 * mm, h - 32 * mm, f"Period: {start}  to  {end}")
    c.drawString(15 * mm, h - 38 * mm, f"Total violations: {len(rows)}")

    counts: dict[str, int] = {}
    for r in rows:
        counts[r["violation_type"]] = counts.get(r["violation_type"], 0) + 1

    y = h - 52 * mm
    c.setFont("Helvetica-Bold", 12)
    c.drawString(15 * mm, y, "Type")
    c.drawString(120 * mm, y, "Count")
    y -= 6 * mm
    c.line(15 * mm, y, 180 * mm, y)
    y -= 8 * mm
    c.setFont("Helvetica", 11)
    for vtype, cnt in sorted(counts.items(), key=lambda kv: -kv[1]):
        c.drawString(15 * mm, y, vtype)
        c.drawString(120 * mm, y, str(cnt))
        y -= 7 * mm
        if y < 20 * mm:
            c.showPage()
            y = h - 20 * mm

    c.showPage()
    c.save()
    return buf.getvalue()
